# Generated by Django 3.2.16 on 2025-01-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified_at',
        ),
    ]
